#include "common/Backtester.hpp"
#include "common/Strategy.hpp"

#include <chrono>
#include <filesystem>
#include <iomanip>
#include <iostream>

using namespace cmf;

namespace
{

void writeReport(const EngineConfig& cfg,
                 const Metrics& metrics,
                 const QuotePair& lastQuote,
                 double elapsedSeconds)
{
    const std::filesystem::path path(cfg.reportPath);
    if (path.has_parent_path())
    {
        std::filesystem::create_directories(path.parent_path());
    }

    std::ofstream out(cfg.reportPath);
    if (!out)
    {
        throw std::runtime_error("cannot write report: " + cfg.reportPath);
    }

    out << "# Performance Report\n\n";
    out << "Generated by `build/bin/hft-market-making`.\n\n";
    out << "## Configuration\n\n";
    out << "- LOB file: `" << cfg.lobPath << "`\n";
    out << "- Trade file: "
        << (cfg.tradePath.empty() ? "(none, crossing fallback)" : "`" + cfg.tradePath + "`")
        << "\n";
    out << "- Processed snapshots: " << metrics.snapshots << "\n";
    out << "- Quote interval: " << cfg.quoteIntervalEvents << " snapshots\n";
    out << "- Order quantity: " << cfg.orderQuantity << "\n";
    out << "- Microprice extension: " << (cfg.useMicropriceExtension ? "enabled" : "disabled")
        << "\n";
    out << "- Gamma: " << cfg.gamma << "\n";
    out << "- Kappa: " << cfg.kappa << "\n\n";

    out << "## Results\n\n";
    out << std::fixed << std::setprecision(10);
    out << "| Metric | Value |\n";
    out << "| --- | ---: |\n";
    out << "| Mark-to-market PnL | " << metrics.markToMarketPnl() << " |\n";
    out << "| Cash | " << metrics.cash << " |\n";
    out << "| Inventory | " << metrics.inventory << " |\n";
    out << "| Last mid | " << metrics.lastMid << " |\n";
    out << "| Turnover | " << metrics.turnover << " |\n";
    out << "| Fees | " << metrics.realizedFees << " |\n";
    out << "| Fills | " << metrics.fills << " |\n";
    out << "| Orders placed | " << metrics.ordersPlaced << " |\n";
    out << "| Cancels | " << metrics.cancels << " |\n";
    out << "| Max abs inventory | " << metrics.maxAbsInventory << " |\n";
    out << "| Last reservation price | " << lastQuote.reservationPrice << " |\n";
    out << "| Last half spread | " << lastQuote.halfSpread << " |\n";
    out << "| Last rolling volatility | " << lastQuote.volatility << " |\n";
    out << "| Runtime seconds | " << elapsedSeconds << " |\n\n";

    out << "## Execution Model\n\n";
    if (cfg.tradePath.empty())
    {
        out << "Crossing-based fallback. Resting buys fill when the replayed best ask is at or "
               "below the order price; resting sells fill when the replayed best bid is at or "
               "above the order price. Cumulative displayed depth across crossed LOB levels "
               "must meet the order size. Fill price is the posted limit price.\n";
    }
    else
    {
        out << "Trade-driven queue depletion using `" << cfg.tradePath
            << "`. At placement, displayed quantity at or better than the order price is "
               "recorded as queue_ahead. Public trades decrement that queue, and orders fill "
               "in full at their posted limit price when the queue reaches zero.\n";
    }
}

} // namespace

int main(int argc, const char* argv[])
{
    try
    {
        const std::string configPath = argc > 1 ? argv[1] : "config/default.conf";
        const EngineConfig cfg = loadConfig(configPath);
        validateConfig(cfg);

        CsvBookReader lobReader(cfg.lobPath, cfg.levels);
        AvellanedaStoikovStrategy strategy(cfg);
        OrderManager orders;
        Metrics metrics;
        BookSnapshot book;
        QuotePair lastQuote;
        lobReader.prepare(book);

        Fill fillBuf[MAX_FILLS_PER_TICK];
        std::optional<CsvTradeReader> tradeReader;
        TradeRecord trade;
        bool hasTrade = false;
        if (!cfg.tradePath.empty())
        {
            tradeReader.emplace(cfg.tradePath);
            hasTrade = tradeReader->next(trade);
        }

        const auto start = std::chrono::steady_clock::now();
        while (lobReader.next(book))
        {
            ++metrics.snapshots;
            metrics.lastMid = book.mid();
            strategy.observe(book);

            if (tradeReader)
            {
                while (hasTrade && trade.timestamp <= book.timestamp)
                {
                    const auto n = orders.processTrade(trade, fillBuf, MAX_FILLS_PER_TICK);
                    for (std::size_t i = 0; i < n; ++i)
                    {
                        applyFill(fillBuf[i], cfg.feeBps, metrics);
                    }
                    hasTrade = tradeReader->next(trade);
                }
            }
            else
            {
                const auto n = orders.matchCrossingOrders(book, fillBuf, MAX_FILLS_PER_TICK);
                for (std::size_t i = 0; i < n; ++i)
                {
                    applyFill(fillBuf[i], cfg.feeBps, metrics);
                }
            }

            if (metrics.snapshots > cfg.warmupEvents &&
                metrics.snapshots % cfg.quoteIntervalEvents == 0)
            {
                metrics.cancels += orders.cancelAll();
                lastQuote = strategy.quote(book, metrics.inventory);
                if (metrics.inventory < cfg.inventoryLimit)
                {
                    const Quantity queueAhead = computeQueueAhead(book, Side::Buy, lastQuote.bid);
                    orders.place(Side::Buy, lastQuote.bid, cfg.orderQuantity, book.timestamp, queueAhead);
                    ++metrics.ordersPlaced;
                }
                if (metrics.inventory > -cfg.inventoryLimit)
                {
                    const Quantity queueAhead = computeQueueAhead(book, Side::Sell, lastQuote.ask);
                    orders.place(Side::Sell, lastQuote.ask, cfg.orderQuantity, book.timestamp, queueAhead);
                    ++metrics.ordersPlaced;
                }
            }

            if (cfg.maxEvents > 0 && metrics.snapshots >= cfg.maxEvents)
            {
                break;
            }
        }

        metrics.cancels += orders.cancelAll();
        const auto end = std::chrono::steady_clock::now();
        const double elapsed = std::chrono::duration<double>(end - start).count();

        writeReport(cfg, metrics, lastQuote, elapsed);

        std::cout << std::fixed << std::setprecision(10);
        std::cout << "snapshots=" << metrics.snapshots << " pnl=" << metrics.markToMarketPnl()
                  << " inventory=" << metrics.inventory << " turnover=" << metrics.turnover
                  << " fills=" << metrics.fills << " report=" << cfg.reportPath << '\n';
    }
    catch (std::exception& ex)
    {
        std::cerr << "HFT market-making app threw an exception: " << ex.what() << std::endl;
        return 1;
    }

    return 0;
}
